### ISSUE TITLE
question: what's the license of byte-monkey?

### ISSUE THREAD

**Issue by monperrus** [mrwilson/byte-monkey#1]
thanks, --Martin

**Comment by mrwilson** [comment]
Hi,

Thanks for pointing this out - I thought I'd added a license but apparently not!

byte-monkey is distributed under the MIT license.

Thanks,

Alex

**Comment by monperrus** [comment]
excellent, thanks.

FYI: we're building on it for doing a chaos controller for the JVM.

**Comment by mrwilson** [comment]
That's cool! Good luck, and please raise issues if there's anything that would make it better. :)
